##
# Jump App Microservices Chart values
#
# PRO Environments
#
##

# Subcharts status
jump-app-cicd:
  enabled: false
jump-app-micros:
  enabled: true
jump-app-argocd:
  enabled: false

# Istio Settings
istio:
  enabled: false
  namespace: istio-system
  mtls: true

# CICD Settings
cicd:
  namespace: jump-app-cicd

# Public domain where apps will be published
appsDomain: apps.acidonpe.sandbox1736.opentlc.com

# Global variables
global:
  apps:
    front-javascript:
      imagetag: master
      multiVersions:
        enabled: true
        imagetag: production
        v1Traffic: 50
        v2Traffic: 50
      replicas: 1
      envVars:
        APP_REF_NAME: jump-app
      containerPorts:
        http:
          containerPort: 3000
          protocol: TCP
      servicePorts:
        http-8080:
          port: 8080
          protocol: TCP
          targetPort: 3000
      public: true
      routeTargetPort: http-8080
      backend: back-golang