apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: gitops-argocd
  namespace: gitops-argocd
spec:
  targetNamespaces:
  - gitops-argocd

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gitops-argocd
  namespace: gitops-argocd 
spec:
  channel: alpha
  name: argocd-operator
  source: community-operators
  sourceNamespace: openshift-marketplace 


  